config/routes.rb
Rails.application.routes.draw do
  root 'companies#index'
  resources :companies do
    resources :survey_responses, only: [:new, :create]
    get 'survey_analysis', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
    extend ActiveHash::Associations::ActiveRecordExtensions

    validates :name, presence: true

    has_many :departments, dependent: :destroy
    has_many :job_functions, dependent: :destroy
    has_many :survey_responses
    belongs_to_active_hash :industry

    accepts_nested_attributes_for :departments, allow_destroy: true
    accepts_nested_attributes_for :job_functions, allow_destroy: true

    def total_absenteeism
        survey_responses.sum(&:absenteeism)
    end

    def total_presenteeism
        survey_responses.sum(&:presenteeism)
    end

    def total_productivity_loss
        survey_responses.sum(&:calculate_productivity_loss)
    end

    def health_condition_response_counts
        health_condition_response_counts = HealthConditionResponse.joins(survey_response: :company)
                                                                .where(survey_responses: { company_id: company_id })
                                                                .group(:health_condition_id)
                                                                .count
    end
end

app/models/department.rb
class Department < ApplicationRecord
  attribute :name, :string
  belongs_to :company, foreign_key: "company_id", optional: true
end

app/models/employment_type.rb
class EmploymentType < ActiveHash::Base
  self.data = [
    { id: 1, category: '正社員' },
    { id: 2, category: 'パート（アルバイトを含む）' },
    { id: 3, category: '派遣' },
    { id: 4, category: '契約' },
    { id: 5, category: '委託' },
    { id: 6, category: 'その他' }
  ]
end

app/models/health_condition.rb
class HealthCondition < ActiveHash::Base
  self.data = [
    { id: 1, category: '0. 健康上の問題や不調はない' },
    { id: 2, category: '1. アレルギーによる疾患（花粉症・アレルギー性結膜炎など）' },
    { id: 3, category: '2. 皮膚の病気・かゆみ（湿疹やアトピー性湿疹など）' },
    { id: 4, category: '3. 感染症による不調（風邪、インフルエンザ、胃腸炎）' },
    { id: 5, category: '4. 胃腸に関する不調（繰り返す下痢、便秘、胃不快感）' },
    { id: 6, category: '5. 手足の関節の痛みや不自由さ（関節炎など）' },
    { id: 7, category: '6. 腰痛' },
    { id: 8, category: '7. 首の不調や肩のこりなど' },
    { id: 9, category: '8. 頭痛（偏頭痛や慢性的な頭痛など）' },
    { id: 10, category: '9. 歯の不調（歯痛など）' },
    { id: 11, category: '10. 精神関する不調（うつ症状（気分の落ち込みなど）、不安感）' },
    { id: 12, category: '11. 睡眠に関する不調（寝ようとしても寝れないなど）' },
    { id: 13, category: '12. 全身の倦怠感、疲労感' },
    { id: 14, category: '13. 眼の不調（視力低下・眼精疲労・ドライアイ・緑内障など）' },
    { id: 15, category: '14. その他不調など' },
  ]
end

app/models/health_condition_response.rb
class HealthConditionResponse < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :survey_response
  belongs_to_active_hash :health_condition
end

app/models/industry.rb
class Industry < ActiveHash::Base
  self.data = [
    { id: 1, category: '運輸業' },
    { id: 2, category: '林業' },
    { id: 3, category: '建設業' },
    { id: 4, category: '製造業' },
    { id: 5, category: '小売業' },
    { id: 6, category: '医療・福祉' },
    { id: 7, category: '飲食業' },
    { id: 8, category: '保育業' }
  ]
end

app/models/job_function.rb
class JobFunction < ApplicationRecord
    belongs_to :company
end

app/models/survey_response.rb
class SurveyResponse < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :health_condition_responses
  belongs_to :company
  belongs_to :department
  belongs_to :job_function
  belongs_to_active_hash :employment_type

  enum age_group: {
    under_teen: 0,
    twenties: 1,
    thirties: 2,
    forties: 3,
    fifties: 4,
    sixties_and_over: 5
  }

  validates :task_volume_completion_level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :task_volume_completion_level, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }

  accepts_nested_attributes_for :health_condition_responses, allow_destroy: true

  def health_condition_ids
    health_condition_responses.map(&:health_condition_id)
  end

  def health_condition_ids=(ids)
    self.health_condition_responses = ids.compact.reject(&:blank?).map do |id|
      health_condition_response = health_condition_responses.find_or_initialize_by(health_condition_id: id)
      health_condition_response
    end
  end

  def presenteeism
    task_volume = self.task_volume_completion_level.to_f / 10
    task_quality = self.task_quality_level.to_f / 10

    presenteeism_score = (1 - task_volume * task_quality) * self.days_with_symptoms.to_f * 20 / 28 * 10000 * 12

    presenteeism_score.floor
  end

  def absenteeism
    absenteeism_score = self.absent_days * 10000
    absenteeism_score
  end

  def calculate_productivity_loss
    presenteeism + absenteeism
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  skip_before_action :verify_authenticity_token

  def index
    @companies = Company.all
    @industries = Industry.all
  end

  def new
    @company = Company.new
    @industries = Industry.all
  end

  def create
    @company = Company.new(company_params)
    
    if @company.save
      redirect_to companies_path, notice: 'Company was successfully created.'
    else
      render :new
    end

  end

  def edit
    @company = Company.find(params[:id])
    @industries = Industry.all
    @departments = @company.departments.all
    @jobFunctions = @company.job_functions.all
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path, notice: '企業情報が正常に更新されました。'
    else
      @industries = Industry.all # エラー時に再度業界リストをロード
      render :edit
    end
  end

  def destroy
    @company = Company.find(params[:id])
    if @company.destroy
      redirect_to companies_path, notice: '企業が正常に削除されました。'
    else
      redirect_to companies_path, alert: '企業の削除に失敗しました。'
    end
  end

  def survey_analysis
    @company = Company.find(params[:id])
    @departments = @company.departments.all
    @jobFunctions = @company.job_functions.all
    @employment_types = EmploymentType.all
    @symptoms = [['腰痛', 5],['頭痛（偏頭痛や慢...', 4], ['睡眠に関する不調...', 2], ['アレルギーによる...', 1], ['その他不調など', 1]]
  end

  private

  def company_params
    params.require(:company).permit(
      :name, 
      :number_of_employees, 
      :industry_id, 
      departments_attributes: [:id, :name, :_destroy],
      job_functions_attributes: [:id, :description, :_destroy]
    )
  end
end

app/controllers/survey_responses_controller.rb
# app/controllers/survey_responses_controller.rb

class SurveyResponsesController < ApplicationController
  def new
    @survey_response = SurveyResponse.new
    @company = Company.find(params[:company_id])
    @departments = @company.departments.all
    @jobFunctions = @company.job_functions.all
    @employment_type = EmploymentType.all
    @health_conditions = HealthCondition.all
  end

  def create
    @survey_response = SurveyResponse.new(survey_response_params)
    if @survey_response.save
      flash[:success] = "アンケートが送信されました。"
      redirect_to root_path
    else
      flash[:error] = "アンケートの送信中にエラーが発生しました。"
      redirect_to new_company_survey_response_path(@company)
    end
  end

  private

  def survey_response_params
    params.require(:survey_response).permit(
      :survey_number,
      :gender,
      :age_group,
      :years_of_service,
      :days_with_symptoms,
      :task_volume_completion_level,
      :task_quality_level,
      :absent_days,
      :company_id,
      :department_id,
      :employment_type_id,
      :job_function_id,
      health_condition_responses_attributes: [:id, :is_most_impactful, :health_condition_id]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/survey_responses_helper.rb
module SurveyResponsesHelper
end

app/views/companies/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>企業情報編集画面</title>
</head>
<body>
    <div class="card card-body">
        <h1>企業情報編集</h1>
    </div>
    <div class="container">
        <%= form_with(model: @company, local: true) do |form| %>
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td>企業名</td>
                    <td><%= form.text_field :name, class: 'form-control' %></td>
                </tr>
                <tr>
                    <td>業界</td>
                    <td>
                    <%= form.collection_select :industry_id, @industries, :id, :category, {include_blank: '選択'}, {class: 'form-control'} %>
                    </td>
                </tr>
                <tr>
                    <td>従業員数</td>
                    <td>
                    <div class="input-group" style="max-width: 200px;">
                        <%= form.text_field :number_of_employees, class: 'form-control' %>
                        <span class="input-group-text">人</span>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td>部署</td>
                    <td id="departmentInputCell">
                        <% @company.departments.each_with_index do |department, index| %>
                            <div class="input-group mb-2">
                                <%= form.fields_for :departments, department do |department_form| %>
                                    <%= department_form.text_field :name, class: 'form-control' %>
                                    <%= department_form.hidden_field :_destroy, value: department_form.object._destroy, id: "departments_#{index}__destroy" %>
                                <% end %>
                                <button class="btn btn-danger btn-sm input-group-append" type="button" onclick="remove_fields(this)">削除</button>
                            </div>
                        <% end %>
                        <button class="btn btn-outline-secondary" type="button" id="addDepartmentInput">＋ 部署を追加</button>
                    </td>
                </tr>
                <tr>
                    <td>業務内容</td>
                    <td id="jobFunctionsInputCell">
                        <% @company.job_functions.each_with_index do |job_function, index| %>
                            <div class="input-group mb-2">
                                <%= form.fields_for :job_functions, job_function do |job_function_form| %>
                                    <%= job_function_form.text_field :description, class: 'form-control' %>
                                    <%= job_function_form.hidden_field :_destroy, value: job_function_form.object._destroy, id: "job_function_form_#{index}__destroy" %>
                                <% end %>
                                <button class="btn btn-danger btn-sm input-group-append" type="button">削除</button>
                            </div>
                        <% end %>
                        <button class="btn btn-outline-secondary" type="button" id="addJobFunctionsInput">＋ 業務内容を追加</button>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="actions d-flex justify-content-center">
                <%= form.submit '更新', class: 'btn btn-primary', style: 'margin-right: 8px;' %>
                <%= link_to 'キャンセル', companies_path, class: 'btn btn-secondary' %>
            </div>
        <% end %>
    </div>
</body>
</html>

<style>
    /* テーブルの左側の見出しの背景色を水色に設定 */
    table.table-bordered th {
        background-color: lightblue;
    }
</style>
<script>
document.addEventListener("DOMContentLoaded", function() {

    initializeExistingRemovalButtons();

    // 既存の削除ボタンに対する処理を初期化
    function initializeExistingRemovalButtons() {
        document.querySelectorAll('.input-group .btn-danger').forEach(button => {
            button.addEventListener('click', function(event) {
                const wrapper = event.target.closest('.input-group');
                const hiddenDestroyInput = wrapper.querySelector("input[type=hidden][name*='_destroy']");
                if (hiddenDestroyInput) {
                    hiddenDestroyInput.value = '1';
                }
                wrapper.style.display = 'none';
            });
        });
    }

    let departmentIndex = <%= @company.departments.count %>;
    let jobFunctionIndex = <%= @company.job_functions.count %>;

    document.getElementById("addDepartmentInput").addEventListener("click", function() {
        addField("departmentInputCell", "departments", departmentIndex++, "name");
    });

    document.getElementById("addJobFunctionsInput").addEventListener("click", function() {
        addField("jobFunctionsInputCell", "job_functions", jobFunctionIndex++, "description");
    });

    function addField(wrapperId, association, index, fieldName) {
        let wrapper = document.getElementById(wrapperId);
        let newFieldWrapper = document.createElement("div");
        newFieldWrapper.classList.add("input-group", "mb-2");

        let newField = document.createElement("input");
        newField.setAttribute("type", "text");
        newField.setAttribute("name", `company[${association}_attributes][${index}][${fieldName}]`);
        newField.classList.add("form-control");

        let hiddenDestroy = document.createElement("input");
        hiddenDestroy.setAttribute("type", "hidden");
        hiddenDestroy.setAttribute("name", `company[${association}_attributes][${index}][_destroy]`);
        hiddenDestroy.value = "false";

        let removeButton = document.createElement("button");
        removeButton.type = "button";
        removeButton.innerText = "削除";
        removeButton.classList.add("btn", "btn-danger", "btn-sm", "input-group-append");

        removeButton.addEventListener("click", function() {
            hiddenDestroy.value = "true";
            newFieldWrapper.style.display = "none";
        });

        newFieldWrapper.appendChild(newField);
        newFieldWrapper.appendChild(hiddenDestroy);
        newFieldWrapper.appendChild(removeButton);
        wrapper.appendChild(newFieldWrapper);
    }
});

</script>

app/views/companies/index.html.erb
<head>
    <title>企業一覧画面</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="form-inline mb-3" style="display: flex; justify-content: space-between">
        <h1>企業一覧</h1>
        <%= link_to '新規登録', new_company_path, class: 'btn btn-primary' %>
    </div>
    <!-- 検索フォーム -->
    <div class="card card-body">
        <div class="form-inline mb-3">
            <form class="form-inline mb-3">
                <div class="form-group mr-2">
                    <label for="exampleInputPassword1" class="form-label">企業名</label>
                    <input type="password" class="form-control mr-2" id="exampleInputPassword1">
                </div>
                <div class="form-group mr-2">
                <label class="pulldown-label">業種</label>
                    <select class="form-control mr-2" name="industry_id">
                        <option value="">ー</option>
                        <% @industries.each do |industry| %>
                            <option value="<%= industry.id %>"><%= industry.category %></option>
                        <% end %>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">検索</button>
            </form>
        </div>
    </div>
    <div class="card">
        <table class="table table-striped">
            <thead class="table-primary">
                <tr>
                    <th>ID</th>
                    <th scope="col">企業名</th>
                    <th scope="col">業種</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <% @companies.each do |company| %>
                    <tr>
                        <th scope="row"><%= company.id %></th>
                        <td><%= company.name %></td>
                        <td><%= company.industry.category %></td>
                        <td>
                            <%= link_to 'アンケートデータ一覧へ', survey_analysis_company_path(company), class: 'btn btn-outline-primary btn-{themecolor} rounded-pill' %>
                            <%= link_to 'アンケート画面へ', new_company_survey_response_path(company), class: 'btn btn-outline-secondary btn-{themecolor} rounded-pill' %>
                        </td>
                        <td>
                            <%= link_to '編集', edit_company_path(company), class: 'btn btn-secondary' %>
                            <%= button_to '削除', company_path(company), method: :delete, data: { confirm: '削除しますか？' }, class: 'btn btn-danger', form: {class: "d-inline"} %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</body>

app/views/companies/new.html.erb
<head>
    <title>企業新規作成画面</title>
</head>
<body>
    <div class="card card-body">
        <h1>企業新規作成</h1>
    </div>
    <div class="container">
        <%= form_with(model: @company, local: true) do |form| %>
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <td>企業名</td>
                    <td><%= form.text_field :name, class: 'form-control' %></td>
                </tr>
                <tr>
                    <td>業界</td>
                    <td>
                    <%= form.collection_select :industry_id, @industries, :id, :category, {include_blank: '選択'}, {class: 'form-control'} %>
                    </td>
                </tr>
                <tr>
                    <td>従業員数</td>
                    <td>
                    <div class="input-group" style="max-width: 200px;">
                        <%= form.text_field :number_of_employees, class: 'form-control' %>
                        <span class="input-group-text">人</span>
                    </div>
                    </td>
                </tr>
                <tr>
                    <td>部署</td>
                    <td id="departmentInputCell">
                        <div class="input-group">
                            <%= form.fields_for :departments, @company.departments.build do |department_form| %>
                                <%= department_form.text_field :name, class: 'form-control' %>
                            <% end %>
                            <button class="btn btn-outline-secondary" type="button" id="addDepartmentInput">＋ 部署を追加</button>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>業務内容</td>
                    <td id="jobFunctionsInputCell">
                    <div class="input-group">
                        <%= form.fields_for :job_functions, @company.job_functions.build do |job_function_form| %>
                            <%= job_function_form.text_field :description, class: 'form-control' %>
                        <% end %>
                        <button class="btn btn-outline-secondary" type="button" id="addJobFunctionsInput">＋ 業務内容を追加</button>
                    </div>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="actions d-flex justify-content-center">
                <%= form.submit '登録', class: 'btn btn-primary', style: 'margin-right: 8px;' %>
                <%= link_to 'キャンセル', companies_path, class: 'btn btn-secondary' %>
            </div>
        <% end %>
    </div>
</body>

<style>
    /* テーブルの左側の見出しの背景色を水色に設定 */
    table.table-bordered th {
        background-color: lightblue;
    }
</style>
<script>
document.addEventListener("DOMContentLoaded", function() {
  let departmentIndex = 1; // 部署用のインデックス
  let jobFunctionIndex = 1; // 業務内容用のインデックス

  document.getElementById("addDepartmentInput").addEventListener("click", function() {
    addField("departmentInputCell", "departments", departmentIndex++, "name");
  });

  document.getElementById("addJobFunctionsInput").addEventListener("click", function() {
    addField("jobFunctionsInputCell", "job_functions", jobFunctionIndex++, "description");
  });

  function addField(wrapperId, association, index, fieldName) {
    var wrapper = document.getElementById(wrapperId);
    var newFieldWrapper = document.createElement("div");
    newFieldWrapper.classList.add("input-group", "mb-2");

    var newField = document.createElement("input");
    newField.setAttribute("type", "text");
    // フィールド名を正しく設定する
    newField.setAttribute("name", `company[${association}_attributes][${index}][${fieldName}]`);
    newField.classList.add("form-control");

    var removeButton = document.createElement("button");
    removeButton.type = "button";
    removeButton.innerText = "削除";
    removeButton.classList.add("btn", "btn-danger", "btn-sm", "input-group-append");

    removeButton.addEventListener("click", function() {
      newFieldWrapper.remove();
      // インデックスをデクリメントする処理は省略。実際には削除された要素に応じてインデックス管理を工夫する必要がある
    });

    newFieldWrapper.appendChild(newField);
    newFieldWrapper.appendChild(removeButton);
    wrapper.appendChild(newFieldWrapper);
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatsueApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/survey_responses/thank_you.html.erb
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <div class="main-body">
        <div class="k-card card text-center border-primary m-5 mx-auto">
        <h5 class="card-header border-primary">
            アンケートのご協力ありがとうございました。
        </h5>
        <p class="card-text m-5">
            入力いただいた内容を分析し、結果を後日皆様にお返しいたします。<br>
            またデータにつきましては、皆様の健康や働き方の改善に役立てるために使用いたします。
        </p>
    </div>
</div>
</body>